<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE viajes [
   <!ELEMENT viajes (austria, italia, francia)>
   <!ELEMENT austria (ciudad+)>
   <!ELEMENT italia (ciudad+)>
   <!ELEMENT francia (ciudad+)>
   <!ELEMENT ciudad (#PCDATA)>
]>

<viajes>
   <austria>
      <ciudad>Viena</ciudad>
   </austria>
   <italia>
      <ciudad>Florencia</ciudad>
      <ciudad>Roma</ciudad>
      <ciudad>Venecia</ciudad>
   </italia>
   <francia>
     <ciudad></ciudad>  
   </francia>
</viajes>